# Generated by Django 4.2.7 on 2025-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_live_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='newsletter_subscription',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
